// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HardwareMetrics = { cpu_usage: number, ram_used_gb: number, ram_total_gb: number, cores_active: number, };
