// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuantumState = { entropy: number, resonance: number, equity: number, active_nodes: number, stability_factor: number, };
